modLoader="javafml"
loaderVersion="47,)"
license="All Rights Reserved, DragN0007"
#issueTrackerURL="https://discord.gg/2WznNTtVac"
[[mods]]
modId="deadlydinos"
version="${0.1}"
displayName="DragN's Deadly Dinos!"
logoFile="deadly_dinos_logo.png"
authors="DragN0007"
description='''
Adds aggressive, prehistoric creatures to your world. Build a strong base to survive.

DragN's Mods Server & Issues Forum: https://discord.gg/jubppqCzXj
'''
[[dependencies.deadlydinos]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.deadlydinos]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
[[dependencies.deadlydinos]]
modId="geckolib"
mandatory=true
versionRange = "[4.4.4,)"
ordering="NONE"
side="BOTH"
[[dependencies.deadlydinos]]
modId="patchouli"
mandatory=true
versionRange = "[1.20.1-84,)"
ordering="NONE"
side="BOTH"